name: PluginCite
version: 1.0
api-version: 1.21
main: fr.citedesiles.plugincite.PluginCite
depend:
  - FancyNpcs
  - FancyHolograms
commands:
  admin:
    description: Commande d'administration
    usage: /admin <commande>